# Generated by Django 4.2.13 on 2024-08-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('check_in_date', models.CharField(max_length=30)),
                ('check_out_date', models.CharField(max_length=30)),
                ('destination', models.CharField(choices=[('Janjehli Resort', 'Janjehli Resort'), ('Kandaghat Shimla Resort', 'Kandaghat Shimla Resort'), ('Kanatal Resort', 'Kanatal Resort'), ('Mussoorie Resort', 'Mussoorie Resort')], max_length=30)),
                ('no_of_persons', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('have_you_availed_membership', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('type_of_room', models.CharField(choices=[('S', 'Studio Apartment'), ('1', '1-Bedroom Apartment'), ('2', '2-Bedroom Apartment')], max_length=30)),
                ('room_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feedbackmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('home', models.TextField(default='Velliangiri Hills,Coimbatore', max_length=100)),
                ('feedback', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Membershipmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(choices=[('India', 'India'), ('Outside India', 'Outside India')], default='India', max_length=20)),
                ('special_request', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Roomsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('studio', models.IntegerField()),
                ('onebed', models.IntegerField()),
                ('twobed', models.IntegerField()),
            ],
        ),
    ]
